# -*- coding: utf-8 -*-
"""KINGSTON v10 figures.

v9 -> v10 changes (seventh-round submission pre-review):
- Fig.5: exclusion categories reverted to the documented screening breakdown
  (55 degenerative compression/T2 change, 2 non-cervical, 10 overlap with the
  earlier >=50-year review) so figure and body text are identical; the
  v9-only 48/7 split had no verifiable per-case source and is withdrawn.
- Fig.8: internal variable name (qc_plus_processing_8_83) removed from the
  figure title; now states the combined processing-plus-QC failure scenario
  (UIH 8, GE 83) in plain English.
- Fig.6: regenerated with a corrected in-figure title - the previous title
  ("No level survives Holm correction") contradicted the C7 Welch-family
  Holm-adjusted p = 0.048; the new title distinguishes the age-adjusted
  family from the Welch family.
- All values from the frozen public-data JSON (results/reanalysis_v10_results.json).

v10.1 (eighth-round pre-review):
- Fig.5: literal "//n" artefact in the exclusion-reason box replaced by a real
  line break; the 10 "earlier review" examinations are now labelled as a
  screening-status remainder rather than a clinical reason.
- Fig.8: colour-bar padding increased so it no longer touches the Panel B title.
- Fig.1, Fig.2, Fig.3 and Fig.7 are now GENERATED by this script from the
  released per-subject data (previously copied from earlier rounds), so all
  eight figures of the manuscript are reproduced by this single script.
"""
import os, shutil, json
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Make paths relative to the script's own location so the script runs from
# either the project workspace or the public repository without edits.
HERE = os.path.dirname(os.path.abspath(__file__))
# The repository layout has this script at <repo_root>/analysis/kingston_figures_v9.py
# and figures live at <repo_root>/figures/. Try to locate the repo root by
# walking up to a directory that contains 'github_kingston_vendor_csa' or, if
# unavailable, fall back to a sibling 'figures/' folder next to HERE.
_candidate = HERE
for _ in range(4):
    if os.path.basename(_candidate) == 'github_kingston_vendor_csa':
        REPO_ROOT = _candidate
        break
    _candidate = os.path.dirname(_candidate)
else:
    REPO_ROOT = os.path.dirname(HERE)  # sibling of analysis/
INTERNAL_BASE = os.environ.get('KINGSTON_INTERNAL_DIR', '')
REPO_FIG_DIR = os.path.join(REPO_ROOT, 'figures')
REPO_FIG_SRC = os.path.join(REPO_ROOT, 'figures_v8')  # previous round figures
os.makedirs(REPO_FIG_DIR, exist_ok=True)
OUT = REPO_FIG_DIR + os.sep  # ensure trailing separator for string concatenation

V9 = json.load(open(os.path.join(HERE, '..', 'results', 'reanalysis_v10_results.json'), encoding='utf-8'))
PUB = pd.read_csv(os.path.join(REPO_ROOT, 'data', 'kingston_15T_per_subject_deidentified.csv'))
C_UIH, C_GE = '#1f77b4', '#d62728'
print(f'[kingston_figures_v9] writing figures to: {OUT}')

# ================= Fig 5: STROBE flow (REDRAWN, all numbers verified) =================
fig, ax = plt.subplots(figsize=(9.2, 11.5))
ax.set_xlim(-2.6, 15.0)
ax.set_ylim(-0.3, 12.5)
ax.axis('off')

BX, BW = 1.6, 8.0  # main column

def box(x, y, w, h, text, fc='#eef3fb', ec='#1f4e79', fs=9, bold=False):
    ax.add_patch(plt.Rectangle((x, y), w, h, fc=fc, ec=ec, lw=1.3))
    ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=fs,
            fontweight='bold' if bold else 'normal')

def arrow_v(x, y1, y2):
    ax.annotate('', xy=(x, y2), xytext=(x, y1),
                arrowprops=dict(arrowstyle='-|>', color='#1f4e79', lw=1.4))

def note_right(y, text, fs=8.0):
    ax.annotate('', xy=(BX + BW + 0.12, y), xytext=(BX + BW + 0.75, y),
                arrowprops=dict(arrowstyle='<|-', color='#8b0000', lw=1.2))
    ax.text(BX + BW + 0.85, y, text, ha='left', va='center', fontsize=fs, color='#8b0000')

def note_left(y, text, fs=7.9):
    ax.annotate('', xy=(BX - 0.12, y), xytext=(BX - 0.75, y),
                arrowprops=dict(arrowstyle='<|-', color='#8b0000', lw=1.2))
    ax.text(BX - 0.85, y, text, ha='right', va='center', fontsize=fs, color='#8b0000')

# Level 1
box(BX, 11.0, BW, 1.4,
    'Two non-overlapping PACS exports of cervical spine MRI\n'
    'export 1: 80 examinations (Jan\u2013Jun 2026, \u226550 y)\n'
    'export 2: 232 examinations (Jul 2023\u2013Jul 2026, no age limit)\n'
    'deduplication: no shared identifier; cross-check (age, sex, scan date)',
    fs=8.0, bold=True)
note_right(11.7, 'excluded before processing (n = 8):\n1 non-UIH/GE (Philips); 3 without\nusable sagittal T2; 4 aged <18 y')
arrow_v(5.6, 11.0, 10.35)

# Level 2: 312 - 8 = 304, vendor split = UIH 90 / GE 214 (Philips already removed)
box(BX, 9.45, BW, 0.9, 'Eligible examinations entering pipeline\nn = 304   (UIH 90 / GE 214)', fs=9.5, bold=True)
note_right(9.9, 'processing incomplete (n = 4):\narchive series unmatchable')
arrow_v(5.6, 9.45, 8.75)

# Level 3
box(BX, 7.85, BW, 0.9, 'Processed with SCT pipeline\nn = 300   (UIH 90 / GE 210)', fs=10, bold=True)

# split arrows
ax.annotate('', xy=(3.4, 7.1), xytext=(4.2, 7.85),
            arrowprops=dict(arrowstyle='-|>', color='#1f4e79', lw=1.4))
ax.annotate('', xy=(7.8, 7.1), xytext=(7.0, 7.85),
            arrowprops=dict(arrowstyle='-|>', color='#1f4e79', lw=1.4))

# Level 4: QC (separated horizontally to avoid overlap)
box(0.2, 5.85, 5.2, 1.05,
    'Automated QC passed: n = 213 (UIH 82 / GE 131)\n'
    'per-vendor mean CSA in 30\u2013120 mm\u00b2 range;\n\u2265100 analysed cord slices',
    fs=8.0)
box(7.6, 5.85, 4.4, 1.05,
    'Automated QC failed: n = 87 (UIH 8 / GE 79)\n'
    'algorithmic CSA outside range or\nsegmentation under-performance',
    fs=8.0, fc='#fff5f5', ec='#8b0000')
note_left(4.85, 'QC-failed examinations were not screened\nfor degenerative compression; the\ntipping-point sensitivity analysis (Fig. 8)\naddresses this stratum.', fs=7.4)

# QC-passed continues into review; QC-failed branches to right-hand note
arrow_v(2.8, 5.85, 5.1)

# Level 5: DCM review with mutually-exclusive categories
box(BX, 3.55, BW, 1.55,
    'Neuroradiological review of source images\n'
    '(single reader, 13 y cervical-MRI experience, blinded to vendor and CSA)\n'
    '213 \u2192 146 (excluded 67; screening-documented exclusions:\n'
    'degenerative cord compression / T2 signal change 55;\n'
    'non-cervical / wrong-region series 2;\n'
    'excluded in the earlier \u226550-y review 10\n'
    '(screening status, not a clinical reason; see text))',
    fs=7.8, fc='#fff8e1', ec='#b8860b')
arrow_v(5.6, 3.55, 2.85)

# Level 6: 1.5T
box(BX, 1.95, BW, 0.9, '1.5 T analytic cohort\nn = 132   (UIH 51 / GE 81)', fs=9.5, bold=True)
note_right(2.4, 'GE 3.0 T (DISCOVERY MR750)\nexcluded after review: n = 14\n(all QC-passed, all GE)')
arrow_v(5.6, 1.95, 1.2)

box(BX, 0.25, BW, 0.9, 'C2\u2013C5 complete-case population\nn = 127   (UIH 51 / GE 76)', fs=9.5, bold=True)

ax.set_title('Participant and examination flow (STROBE, vendor-stratified)',
             fontsize=12.5, fontweight='bold', y=0.995)
fig.tight_layout()
import os
os.makedirs(OUT, exist_ok=True)
_p5 = OUT + 'fig5_strobe_flow_vendor.png'
_p5p = OUT + 'fig5_strobe_flow_vendor.pdf'
fig.savefig(_p5, dpi=300, bbox_inches='tight')
fig.savefig(_p5p, bbox_inches='tight')
print('saved Fig.5:', os.path.exists(_p5), os.path.getsize(_p5) if os.path.exists(_p5) else 'NA')
plt.close(fig)
print('Fig.5 redrawn: QC boxes separated; mutually-exclusive exclusion categories; '
      'no overlap; consistent with body-text narrative')

# ================= Fig 8: tipping 2D (TRUE 2D heatmap, delta x sigma scale) =================
grid = V9['tipping_2d_v9']
deltas = np.array(grid['GE_sigma1.0']['deltas'])
sigma_levels = [1.0, 1.25, 1.5]
panels = [('GE', 'A. GE-anchored scenario'), ('symmetric', 'B. Symmetric shift scenario')]

fig, axes = plt.subplots(1, 2, figsize=(12.0, 4.8), sharey=True)
for ax, (anchor, title) in zip(axes, panels):
    # Build a 2D matrix: rows = sigma scale, cols = delta
    Z = np.zeros((len(sigma_levels), len(deltas)))
    for i, sc in enumerate(sigma_levels):
        Z[i, :] = np.array(grid[f'{anchor}_sigma{sc}']['tost_p'])
    im = ax.imshow(Z, aspect='auto', origin='lower', cmap='RdYlGn_r',
                   vmin=0, vmax=0.25,
                   extent=[deltas.min(), deltas.max(), 0, len(sigma_levels)])
    # y-axis ticks as sigma scale
    ax.set_yticks([0.5, 1.5, 2.5])
    ax.set_yticklabels([f'\u00d7{s:.2f}' for s in sigma_levels], fontsize=8)
    ax.set_ylabel('SD scale factor (\u03c3)', fontsize=9)
    # overlay p=0.05 contour
    cs = ax.contour(deltas, [0.5, 1.5, 2.5], Z, levels=[0.05], colors='k', linewidths=1.6)
    # tipping values (annotate near the contour intersection)
    for i, sc in enumerate(sigma_levels):
        tip_v = V9['tipping_point_v9']['scenarios']['qc_plus_processing_8_83']['grid_1d'][f'{anchor}_sigma{sc}']['upper_delta']
        if tip_v is not None:
            ax.plot(tip_v, i + 0.5, 'ko', mfc='yellow', mec='black', ms=8, zorder=5)
            ax.annotate(f'+{tip_v:.1f}', xy=(tip_v, i + 0.5),
                        xytext=(tip_v + 1.2, i + 0.5),
                        fontsize=8.5, color='black', va='center')
    ax.set_xlabel('Assumed vendor difference in missing stratum,\nUIH \u2212 GE (mm\u00b2)', fontsize=9)
    ax.set_title(title, fontsize=10.5, pad=12)
    # observed base diff
    base_d = V9['tipping_point_v9']['d_observed_base']
    ax.axvline(base_d, color='#1f77b4', lw=1.4, ls='-.', alpha=0.85, zorder=4)
    ax.annotate('observed\nbase diff', xy=(base_d, 2.6), fontsize=7.5,
                color='#1f77b4', ha='center')
fig.subplots_adjust(left=0.065, right=0.865, top=0.78, bottom=0.20, wspace=0.14)
cax = fig.add_axes([0.885, 0.26, 0.018, 0.46])
cb = fig.colorbar(im, cax=cax)
cb.set_label('TOST p value (\u00b15 mm\u00b2)', fontsize=9)
fig.suptitle('Conditional tipping-point sensitivity (two-dimensional heatmap, delta \u00d7 SD scale). '
             'Yellow dots: tipping thresholds, combined processing-plus-QC failure scenario '
             '(UIH 8, GE 83).',
             fontsize=10.5, y=0.97)
_p8 = OUT + 'fig8_tipping_2d.png'
_p8p = OUT + 'fig8_tipping_2d.pdf'
fig.savefig(_p8, dpi=300, bbox_inches='tight')
fig.savefig(_p8p, bbox_inches='tight')
print('saved Fig.8:', os.path.exists(_p8), os.path.getsize(_p8) if os.path.exists(_p8) else 'NA')
plt.close(fig)
print('Fig.8 redrawn as true 2D heatmap (delta x sigma) with p=0.05 contour and tipping dots')

# ================= Fig 4: equivalence dual endpoint (update footnote values) =================
me = V9['main_endpoint']['complete_case']
wcx = V9['whole_cord']
fig, axes = plt.subplots(1, 2, figsize=(10, 4.2))
for ax, (name, d, lo, hi, pv) in zip(axes, [
        ('C2\u2013C5 mean (complete case, n = 127)', me['diff'], me['ci_lo'], me['ci_hi'], me['p']),
        ('Whole-cord mean (n = 132)', wcx['diff'], wcx['ci_lo'], wcx['ci_hi'], wcx['p'])]):
    ax.errorbar([d], [0], xerr=[[d - lo], [hi - d]], fmt='o', color='#1f4e79',
                capsize=5, markersize=8, lw=1.8)
    ax.axvline(-5, color='#8b0000', ls='--', lw=1.2)
    ax.axvline(5, color='#8b0000', ls='--', lw=1.2)
    ax.axvline(0, color='#666666', ls='-', lw=0.8)
    ax.fill_betweenx([-1, 1], -5, 5, color='#2e7d32', alpha=0.07)
    ax.set_xlim(-7, 7); ax.set_ylim(-0.8, 0.8)
    ax.set_xlabel('UIH \u2212 GE difference (mm\u00b2)', fontsize=9.5)
    ax.set_title(f'{name}\ndiff = {d:.2f} mm\u00b2; Welch p = {pv:.3f}', fontsize=9.5)
    ax.set_yticks([])
axes[0].annotate(f'TOST p = {me["tost_p"]:.4f}', xy=(0.5, -0.55), xycoords='axes fraction',
                 fontsize=9, ha='center', color='#2e7d32')
axes[1].annotate(f'TOST p = {wcx["tost_p"]:.4f}', xy=(0.5, -0.55), xycoords='axes fraction',
                 fontsize=9, ha='center', color='#2e7d32')
fig.suptitle('Equivalence testing against \u00b15 mm\u00b2 (90% CIs)', fontsize=11, fontweight='bold')
fig.tight_layout(rect=[0, 0, 1, 0.94])
_p4 = OUT + 'fig4_equivalence_dual_endpoint.png'
_p4p = OUT + 'fig4_equivalence_dual_endpoint.pdf'
fig.savefig(_p4, dpi=300)
fig.savefig(_p4p)
print('saved Fig.4:', os.path.exists(_p4), os.path.getsize(_p4) if os.path.exists(_p4) else 'NA')
plt.close(fig)
print('Fig.4 regenerated with v9 values')
print('DONE figures_v10 ->', OUT)

# ================= Fig 6: per-level CSA (corrected in-figure title; v10) =================
pub = pd.read_csv(os.path.join(REPO_ROOT, 'data', 'kingston_15T_per_subject_deidentified.csv'))
levels = ['C2', 'C3', 'C4', 'C5', 'C6', 'C7']
fig, ax = plt.subplots(figsize=(7.0, 4.8))
x = np.arange(6)
for vendor, c, off, dx in [('UIH', C_UIH, -0.17, 13), ('GE', C_GE, 0.17, -13)]:
    m = [pub[pub.vendor == vendor][lv].mean() for lv in levels]
    se = [pub[pub.vendor == vendor][lv].sem() for lv in levels]
    n = [int(pub[pub.vendor == vendor][lv].notna().sum()) for lv in levels]
    ax.errorbar(x + off, m, yerr=se, fmt='o-', color=c, capsize=4, lw=1.8,
                markersize=7, label=vendor)
    for xi, mi, ni in zip(x + off, m, n):
        ax.annotate(str(ni), xy=(xi, mi), xytext=(dx, -3), textcoords='offset points',
                    ha='left' if dx > 0 else 'right', va='center', fontsize=7.5, color=c)
ax.set_xticks(x); ax.set_xticklabels(levels)
ax.set_xlabel('Vertebral level'); ax.set_ylabel('Per-level CSA (mm$^2$)')
ax.set_title('Per-level CSA by vendor (1.5 T cohort; exploratory)\n'
             'Holm-corrected: no level in the age-adjusted family;\n'
             'C7 met the Welch-family threshold (p = 0.048)',
             fontsize=10)
ax.legend(frameon=False, loc='lower left', fontsize=9)
ax.text(0.99, 0.02, 'small numbers = per-level available n', transform=ax.transAxes,
        ha='right', fontsize=7.8, color='#666666')
fig.tight_layout()
_p6 = OUT + 'fig6_perlevel_exploratory.png'
_p6p = OUT + 'fig6_perlevel_exploratory.pdf'
fig.savefig(_p6, dpi=300)
fig.savefig(_p6p)
plt.close(fig)
print('saved Fig.6 (corrected title):', os.path.exists(_p6))
print('DONE figures_v10 ->', OUT)

# ================= Fig 1: C2-C5 main endpoint boxplot (v10.1: generated from public data) =================
from scipy import stats as st
plt.rcParams.update({'font.size': 10, 'axes.spines.top': False, 'axes.spines.right': False})
cc = PUB[PUB[['C2', 'C3', 'C4', 'C5']].notna().all(axis=1)].copy()
fig, ax = plt.subplots(figsize=(4.8, 5.4))
data = [cc[cc.vendor == 'UIH'].c2c5_mean_csa_mm2.values,
        cc[cc.vendor == 'GE'].c2c5_mean_csa_mm2.values]
bp = ax.boxplot(data, widths=0.5, patch_artist=True, showfliers=False,
                medianprops=dict(color='black', lw=1.5))
for patch, c in zip(bp['boxes'], [C_UIH, C_GE]):
    patch.set_facecolor(c); patch.set_alpha(0.55); patch.set_edgecolor(c)
for i, (d, c) in enumerate(zip(data, [C_UIH, C_GE]), start=1):
    x = np.random.default_rng(1).normal(i, 0.05, len(d))
    ax.scatter(x, d, s=12, color=c, alpha=0.55, zorder=3, edgecolors='none')
ax.set_xticklabels([f'UIH\n(n = {len(data[0])})', f'GE\n(n = {len(data[1])})'])
ax.set_ylabel('Mean C2\u2013C5 CSA (mm$^2$)')
ax.set_title('Post-hoc revised main endpoint:/nmean C2\u2013C5 CSA by vendor (1.5 T, complete-case)',
             fontsize=11)
me = V9['main_endpoint']['complete_case']
ax.set_ylim(48, 97)
ax.annotate(f'Difference = {me["diff"]:.2f} mm$^2$, 90% CI {me["ci_lo"]:.2f} to {me["ci_hi"]:.2f}\n'
            f'Welch\u2019s t-test p = {me["p"]:.3f}; TOST (\u00b15 mm$^2$, post-hoc margin) p = {me["tost_p"]:.3f}',
            xy=(0.5, 0.035), xycoords='axes fraction', ha='center', fontsize=8.6,
            bbox=dict(boxstyle='round', fc='#f5f5f5', ec='0.6'))
fig.tight_layout()
fig.savefig(OUT + 'fig1_c2c5_primary_boxplot.png', dpi=300)
fig.savefig(OUT + 'fig1_c2c5_primary_boxplot.pdf')
plt.close(fig)
print('saved Fig.1 (regenerated from public data)')

# ================= Fig 2: whole-cord CSA vs age, with 95% CI bands (v10.1) =================
fig, ax = plt.subplots(figsize=(7.8, 4.6))

def _fit_band(x, y, color, label):
    sl, ic, r, p_, se_ = st.linregress(x, y)
    n = len(x); xbar = x.mean()
    sxx = np.sum((x - xbar) ** 2)
    yhat = sl * x + ic
    mse = np.sum((y - yhat) ** 2) / (n - 2)
    xs = np.linspace(x.min(), x.max(), 200)
    se_line = np.sqrt(mse * (1.0 / n + (xs - xbar) ** 2 / sxx))
    tcrit = st.t.ppf(0.975, n - 2)
    ax.fill_between(xs, sl * xs + ic - tcrit * se_line, sl * xs + ic + tcrit * se_line,
                    color=color, alpha=0.13, lw=0)
    ax.plot(xs, sl * xs + ic, color=color, lw=1.5, alpha=0.9,
            label=f'{label}: slope = {sl:.3f} mm$^2$/y (p = {p_:.2f})' if p_ >= 0.005
            else f'{label}: slope = {sl:.3f} mm$^2$/y (p < 0.01)')

for vendor, c in [('UIH', C_UIH), ('GE', C_GE)]:
    s = PUB[PUB.vendor == vendor]
    ax.scatter(s.age, s.whole_cord_mean_csa_mm2, color=c, s=24, alpha=0.65,
               edgecolor='none', label=None)
    _fit_band(s.age.values.astype(float), s.whole_cord_mean_csa_mm2.values.astype(float), c, vendor)
_fit_band(PUB.age.values.astype(float), PUB.whole_cord_mean_csa_mm2.values.astype(float),
          'black', 'Overall')
ax.get_lines()[-1].set_linestyle('--')
ax.set_xlabel('Age (years)'); ax.set_ylabel('Whole-cord mean CSA (mm$^2$)')
ax.set_title('Whole-cord CSA vs age by vendor (shading: 95% CI of the fit)', fontsize=11)
ax.legend(frameon=False, fontsize=8.5, loc='center left', bbox_to_anchor=(1.02, 0.5))
fig.tight_layout()
fig.savefig(OUT + 'fig2_wholecord_vs_age.png', dpi=300)
fig.savefig(OUT + 'fig2_wholecord_vs_age.pdf')
plt.close(fig)
print('saved Fig.2 (regenerated from public data, 95% CI bands added)')

# ================= Fig 3: normality assessment (v10.1: public data) =================
fig, axes = plt.subplots(1, 3, figsize=(11.5, 4.0))
u_vals = PUB[PUB.vendor == 'UIH'].whole_cord_mean_csa_mm2.values
g_vals = PUB[PUB.vendor == 'GE'].whole_cord_mean_csa_mm2.values
ax = axes[0]
bins = np.linspace(min(u_vals.min(), g_vals.min()), max(u_vals.max(), g_vals.max()), 14)
ax.hist(u_vals, bins=bins, alpha=0.55, color=C_UIH, label='UIH', edgecolor='white')
ax.hist(g_vals, bins=bins, alpha=0.55, color=C_GE, label='GE', edgecolor='white')
ax.set_xlabel('Whole-cord mean CSA (mm$^2$)'); ax.set_ylabel('Count')
ax.set_title('Distribution', fontsize=10)
ax.legend(frameon=False, fontsize=9)
r2 = {}
for ax, vals, c, name in [(axes[1], u_vals, C_UIH, 'UIH'), (axes[2], g_vals, C_GE, 'GE')]:
    osm, osr = st.probplot(vals, dist='norm')
    ax.scatter(osm[0], osm[1], color=c, s=18, alpha=0.7, edgecolor='none')
    xs = np.array([osm[0].min(), osm[0].max()])
    ax.plot(xs, osr[0] * xs + osr[1], color='black', lw=1, ls='--')
    sw = st.shapiro(vals).pvalue
    r2[name] = osr[2] ** 2 if len(osr) > 2 else np.nan
    ax.set_title(f'{name} Q\u2013Q plot\nShapiro\u2013Wilk p = {sw:.3f}', fontsize=10)
    ax.set_xlabel('Theoretical'); ax.set_ylabel('Sample quantiles')
fig.suptitle('Normality assessment of whole-cord CSA by vendor', fontsize=11)
fig.tight_layout()
fig.savefig(OUT + 'fig3_normality_qq_per_vendor.png', dpi=300)
fig.savefig(OUT + 'fig3_normality_qq_per_vendor.pdf')
plt.close(fig)
print('saved Fig.3 (regenerated from public data); QQ R2: '
      + ', '.join(f'{k}={v:.3f}' for k, v in r2.items()))

# ================= Fig 7: margin sensitivity, both endpoints (v10.1) =================
from matplotlib.patches import Patch
fig, axes = plt.subplots(1, 2, figsize=(9.6, 4.2))
for ax, key, title in [
        (axes[0], 'margin_sensitivity_wholecord_v8', 'Whole-cord endpoint (n = 132)'),
        (axes[1], 'margin_sensitivity_c2c5_v8', 'C2\u2013C5 main endpoint (complete-case n = 127)')]:
    ms = V9[key]
    margins = [m['margin_mm2'] for m in ms['margins']]
    tosts = [m['tost_p'] for m in ms['margins']]
    colors = ['#d62728' if t >= 0.05 else '#2ca02c' for t in tosts]
    bars = ax.bar([f'\u00b1{m:.0f}' for m in margins], tosts, color=colors,
                  edgecolor='black', lw=0.6)
    ax.axhline(0.05, color='black', ls='--', lw=1)
    ax.set_xlabel('Equivalence margin (mm$^2$)')
    ax.set_ylabel('TOST p value')
    ax.set_title(title, fontsize=10)
    for b, t in zip(bars, tosts):
        lab = 'p < 0.001' if t < 0.0005 else f'p = {t:.3f}'
        ax.text(b.get_x() + b.get_width() / 2, t + 0.006, lab, ha='center', fontsize=8.4)
    ax.set_ylim(0, max(tosts) * 1.18)
handles = [Patch(fc='#d62728', label='equivalence NOT supported (p \u2265 0.05)'),
           Patch(fc='#2ca02c', label='equivalence supported (p < 0.05)')]
axes[0].legend(handles=handles, frameon=False, fontsize=8, loc='upper right')
fig.suptitle('Sensitivity of the equivalence conclusion to margin choice (exploratory, post-hoc margin)',
             fontsize=11)
fig.tight_layout(rect=[0, 0, 1, 0.93])
fig.savefig(OUT + 'fig7_margin_sensitivity.png', dpi=300)
fig.savefig(OUT + 'fig7_margin_sensitivity.pdf')
plt.close(fig)
print('saved Fig.7 (regenerated from public data)')

print('\nAll 8 figures of the manuscript are now generated by this single script '
      'from the released data (figures 1-8).')
